[package]
name = "sph"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.16.1"
num = "0.4.3"
num-traits = "0.2.19"
rand = { version = "0.8.5", features = ["small_rng"] }
wgpu = "23.0.0"

[[bin]]
name = "playground"
path = "src/main.rs"
