[package]
name = "sph"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
ndarray = "0.16.1"
num = "0.4.3"
num-traits = "0.2.19"
paste = "1.0.15"
rand = { version = "0.8.5", features = ["small_rng"] }

[[bin]]
name = "playground"
path = "src/main.rs"
